function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t454_setLogoPadding(recid){if($(window).width()>980){var t454__menu=$('#rec'+recid+' .t454');var t454__logo=t454__menu.find('.t454__logowrapper');var t454__leftpart=t454__menu.find('.t454__leftwrapper');var t454__rightpart=t454__menu.find('.t454__rightwrapper');t454__leftpart.css("padding-right",t454__logo.width()/2+50);t454__rightpart.css("padding-left",t454__logo.width()/2+50)}}
function t454_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t454__list_item a[href='"+url+"']").addClass("t-active");$(".t454__list_item a[href='"+url+"/']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t454__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t454__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t454_checkAnchorLinks(recid){if($(window).width()>=960){var t454_navLinks=$("#rec"+recid+" .t454__list_item a:not(.tooltipstered)[href*='#']");if(t454_navLinks.length>0){t454_catchScroll(t454_navLinks)}}}
function t454_catchScroll(t454_navLinks){var t454_clickedSectionId=null,t454_sections=new Array(),t454_sectionIdTonavigationLink=[],t454_interval=100,t454_lastCall,t454_timeoutId;t454_navLinks=$(t454_navLinks.get().reverse());t454_navLinks.each(function(){var t454_cursection=t454_getSectionByHref($(this));if(typeof t454_cursection.attr("id")!="undefined"){t454_sections.push(t454_cursection)}
t454_sectionIdTonavigationLink[t454_cursection.attr("id")]=$(this)});t454_updateSectionsOffsets(t454_sections);$(window).bind('resize',t_throttle(function(){t454_updateSectionsOffsets(t454_sections)},200));$('.t454').bind('displayChanged',function(){t454_updateSectionsOffsets(t454_sections)});setInterval(function(){t454_updateSectionsOffsets(t454_sections)},5000);t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId);t454_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t454_navLinks.removeClass('t-active');t454_sectionIdTonavigationLink[t454_getSectionByHref($(this)).attr("id")].addClass('t-active');t454_clickedSectionId=t454_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t454_now=new Date().getTime();if(t454_lastCall&&t454_now<(t454_lastCall+t454_interval)){clearTimeout(t454_timeoutId);t454_timeoutId=setTimeout(function(){t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)},t454_interval-(t454_now-t454_lastCall))}else{t454_lastCall=t454_now;t454_clickedSectionId=t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId)}})}
function t454_updateSectionsOffsets(sections){$(sections).each(function(){var t454_curSection=$(this);t454_curSection.attr("data-offset-top",t454_curSection.offset().top)})}
function t454_getSectionByHref(curlink){var t454_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t454_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t454_curLinkValue.substring(1)+"']")}}
function t454_highlightNavLinks(t454_navLinks,t454_sections,t454_sectionIdTonavigationLink,t454_clickedSectionId){var t454_scrollPosition=$(window).scrollTop(),t454_valueToReturn=t454_clickedSectionId;if(t454_sections.length!=0&&t454_clickedSectionId==null&&t454_sections[t454_sections.length-1].attr("data-offset-top")>(t454_scrollPosition+300)){t454_navLinks.removeClass('t-active');return null}
$(t454_sections).each(function(e){var t454_curSection=$(this),t454_sectionTop=t454_curSection.attr("data-offset-top"),t454_id=t454_curSection.attr('id'),t454_navLink=t454_sectionIdTonavigationLink[t454_id];if(((t454_scrollPosition+300)>=t454_sectionTop)||(t454_sections[0].attr("id")==t454_id&&t454_scrollPosition>=$(document).height()-$(window).height())){if(t454_clickedSectionId==null&&!t454_navLink.hasClass('t-active')){t454_navLinks.removeClass('t-active');t454_navLink.addClass('t-active');t454_valueToReturn=null}else{if(t454_clickedSectionId!=null&&t454_id==t454_clickedSectionId){t454_valueToReturn=null}}
return!1}});return t454_valueToReturn}
function t454_setPath(){}
function t454_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t454_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-80px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t454_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t454").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t454_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t454"),burger=el.find(".t454__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t454_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}